language: erlang
otp_release:
  - 22.1
  - 21.3
  - 20.3
  - 19.3
  - 18.3
before_script:
  - rebar get-deps
script: rebar compile eunit
after_script:
  - rebar clean
branches:
  only:
    - master
notifications:
  email: false
